---
board: ["gishu@0.1.0", "gishu@0.2.0"]
include:
  - board: gishu@0.1.0
    artifact-name: gishu-0.1.0
  - board: gishu@0.1.0
    artifact-name: gishu-0.1.0-logging
    snippet: zmk-usb-logging gishu-logging
  - board: gishu@0.2.0
    artifact-name: gishu-0.2.0
  - board: gishu@0.2.0
    artifact-name: gishu-0.2.0-logging
    snippet: zmk-usb-logging gishu-logging
